### PR TITLE
fixing broken push

### PR DESCRIPTION
**Pull request by antoonh**
I've changed a couple of the API calls to work with "Access Token" headers and "Content-type" headers. This allows me to push notes again.

### CODE REVIEW

**Comment by fbartels** [comment]
Hi Antoonh,

imho your pull request contains way too many whitespace changes (deleting blank lines and replacing tabs with spaces at other places). I would welcome if you could clean up your pull request to only contain the header changes.

PS: for me the script still works in its current version

**Comment by antoonh** [comment]
Sure.

Not that well versed with all this.

Bear with me. ..

**Comment by fbartels** [comment]
Hi,
btw. inspired by your pull request I also started implementing the new auth schema in my experimental branch. With this I also try to refactor the pushing altogether to have one call and not anymore several cases per note/link/file.

You can see my current state at https://github.com/fbartels/pushbullet-bash/blob/experimental/pushbullet

**Comment by fbartels** [comment]
Hi Antoonh,

I just opened a pull request with my refactored code. You can find it at #49.

**Comment by fbartels** [comment]
Hi, @Red5d you can close this pull request as this one is outdated.

**Pull request closed without merging**
