### PR TITLE
Fix: Deleted devices  | Add: push link with body

### PR DESCRIPTION
**Pull request by Farbdose**
Fix: Deleted devices are not removed but marked as active:false so we get more idens than nicknames

New: Added "body" to link push, because the pushbullet api supports it

### CODE REVIEW

**Comment by fbartels** [comment]
Hi Farbdose,
may I propose to add the body after giving the link? This way the message body would still be optional and it should not break any existing environments.

**Comment by Farbdose** [comment]
Hi fbartels,
thx for the advise - i simply never used the script without my body implementation just like you never used it with it xD

**Comment by Farbdose** [comment]
Thats strange have you greped with
active:\"true or
active\"\:true ? 
(There were some transposed characters)

**Comment by fbartels** [comment]
It was indeed my fault, seems I have messed up while doing the merge. Instead of grepping for active\"\:true I grepped for active:\"true which is why it failed. I have now reapplied your patch end everything is fine.

**Pull request merged**
